<?php require_once APP_ROOT . '/views/inc/components/header.php'; ?>
<?php require_once APP_ROOT . '/views/components/v_premiseofficer_sidebar.php'; ?>


<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/css/admin/dashboard_style.css">

<!-- Material Symbols -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

<!-- Link to Schedule CSS -->
<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/css/premiseofficer/schedule_style.css">

<!-- Schedule Content -->
<div class="main-content">
    <div class="schedule-layout">
        <!-- Calendar Section -->
        <div class="calendar-container">
            <div class="calendar-controls">
                <select id="monthSelect" class="month-select">
                    <option value="0">January</option>
                    <option value="1">February</option>
                    <option value="2">March</option>
                    <option value="3">April</option>
                    <option value="4">May</option>
                    <option value="5">June</option>
                    <option value="6">July</option>
                    <option value="7">August</option>
                    <option value="8">September</option>
                    <option value="9">October</option>
                    <option value="10" selected>November</option>
                    <option value="11">December</option>
                </select>
                
                <select id="yearSelect" class="year-select">
                    <option value="2023">2023</option>
                    <option value="2024" selected>2024</option>
                    <option value="2025">2025</option>
                </select>
            </div>

            <div class="calendar">
                <div class="calendar-header">
                    <div class="day-name">MON</div>
                    <div class="day-name">TUE</div>
                    <div class="day-name">WED</div>
                    <div class="day-name">THU</div>
                    <div class="day-name">FRI</div>
                    <div class="day-name">SAT</div>
                    <div class="day-name">SUN</div>
                </div>
                
                <div class="calendar-body" id="calendarBody">
                    <!-- Calendar dates will be generated by JavaScript -->
                </div>
            </div>
        </div>

        <!-- Shift Details Panel -->
        <div class="shift-details-panel">
            <div class="shift-details" id="shiftDetails">
                <div class="shift-header">
                    <h3>Schedule Details</h3>
                    <span class="selected-date" id="selectedDate">Select a date</span>
                </div>
                
                <div class="shift-content" id="shiftContent">
                    <div class="no-selection">
                        <span class="material-symbols-outlined no-selection-icon">event</span>
                        <p>Click on a date to view your schedule</p>
                    </div>
                </div>

                <!-- Shift Information Template (hidden) -->
                <div class="shift-info-template" id="shiftInfoTemplate" style="display: none;">
                    <div class="shift-card">
                        <div class="shift-status">
                            <span class="status-badge" id="shiftStatus">Scheduled</span>
                        </div>
                        
                        <div class="shift-details-grid">
                            <div class="detail-item">
                                <span class="material-symbols-outlined detail-icon">location_on</span>
                                <div class="detail-content">
                                    <span class="detail-label">Location</span>
                                    <span class="detail-value" id="shiftLocation">-</span>
                                </div>
                            </div>
                            
                            <div class="detail-item">
                                <span class="material-symbols-outlined detail-icon">access_time</span>
                                <div class="detail-content">
                                    <span class="detail-label">Shift Time</span>
                                    <span class="detail-value" id="shiftTime">-</span>
                                </div>
                            </div>
                            
                            <div class="detail-item">
                                <span class="material-symbols-outlined detail-icon">business</span>
                                <div class="detail-content">
                                    <span class="detail-label">Shift Type</span>
                                    <span class="detail-value" id="shiftType">-</span>
                                </div>
                            </div>
                            
                            <div class="detail-item">
                                <span class="material-symbols-outlined detail-icon">supervisor_account</span>
                                <div class="detail-content">
                                    <span class="detail-label">Supervisor</span>
                                    <span class="detail-value" id="shiftSupervisor">-</span>
                                </div>
                            </div>
                        </div>
                        
                        <div class="shift-notes">
                            <div class="notes-header">
                                <span class="material-symbols-outlined">note</span>
                                <h4>Additional Notes</h4>
                            </div>
                            <p id="shiftNotes">No additional notes for this shift.</p>
                        </div>
                    </div>
                </div>

                <!-- No Shift Template (hidden) -->
                <div class="no-shift-template" id="noShiftTemplate" style="display: none;">
                    <div class="no-shift-card">
                        <span class="material-symbols-outlined no-shift-icon">free_breakfast</span>
                        <h4>No Shift Scheduled</h4>
                        <p>You have no scheduled shifts for this date.</p>
                        <div class="day-off-badge">
                            <span class="material-symbols-outlined">beach_access</span>
                            Day Off
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="<?php echo URL_ROOT; ?>/js/components/sidebar.js"></script>
<script src="<?php echo URL_ROOT; ?>/js/premiseofficer/schedule.js"></script>
<?php require_once APP_ROOT . '/views/inc/components/footer.php'; ?>