

<!-- Material Icons -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<!-- Link to Schedule CSS -->
<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/css/premiseOfficer/schedule_style.css">

<!-- Schedule Content -->
<div class="main-content">
    <div class="schedule-layout">
        <!-- Calendar Section -->
        <div class="calendar-container">
            <div class="calendar-controls">
                <button class="nav-btn" id="prevMonth">
                    <span class="material-icons">chevron_left</span>
                </button>
                <div class="current-month-year">
                    <span id="currentMonthYear">December 2024</span>
                </div>
                <button class="nav-btn" id="nextMonth">
                    <span class="material-icons">chevron_right</span>
                </button>
            </div>

            <div class="calendar">
                <div class="calendar-header">
                    <div class="day-name">MON</div>
                    <div class="day-name">TUE</div>
                    <div class="day-name">WED</div>
                    <div class="day-name">THU</div>
                    <div class="day-name">FRI</div>
                    <div class="day-name">SAT</div>
                    <div class="day-name">SUN</div>
                </div>
                
                <div class="calendar-body" id="calendarBody">
                    <!-- Calendar dates will be generated by JavaScript -->
                </div>
            </div>
            
            <div class="calendar-legend">
                <div class="legend-item">
                    <div class="legend-color work-day"></div>
                    <span>Work Day</span>
                </div>
                <div class="legend-item">
                    <div class="legend-color leave-day"></div>
                    <span>Approved Leave</span>
                </div>
                <div class="legend-item">
                    <div class="legend-color today"></div>
                    <span>Today</span>
                </div>
            </div>
        </div>

        <!-- Shift Details Panel -->
        <div class="shift-details-panel">
            <div class="shift-details" id="shiftDetails">
                <div class="shift-header">
                    <h3>Schedule Details</h3>
                    <span class="selected-date" id="selectedDate">Select a date</span>
                </div>
                
                <div class="shift-content" id="shiftContent">
                    <div class="no-selection">
                        <span class="material-icons no-selection-icon">event</span>
                        <p>Click on a date to view your schedule</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const calendarBody = document.getElementById('calendarBody');
    const currentMonthYearSpan = document.getElementById('currentMonthYear');
    const selectedDateSpan = document.getElementById('selectedDate');
    const shiftContent = document.getElementById('shiftContent');
    const prevMonthBtn = document.getElementById('prevMonth');
    const nextMonthBtn = document.getElementById('nextMonth');
    
    let currentDate = new Date();
    let currentMonth = currentDate.getMonth();
    let currentYear = currentDate.getFullYear();
    let selectedDay = null;
    
    // Generate calendar for a specific month and year
    function generateCalendar(month, year) {
        const firstDay = new Date(year, month, 1);
        const lastDay = new Date(year, month + 1, 0);
        const daysInMonth = lastDay.getDate();
        const startingDayOfWeek = firstDay.getDay() === 0 ? 6 : firstDay.getDay() - 1; // Monday = 0
        
        const today = new Date();
        const isCurrentMonth = today.getFullYear() === year && today.getMonth() === month;
        const todayDate = today.getDate();
        
        calendarBody.innerHTML = '';
        
        // Update month/year display
        const monthNames = [
            'January', 'February', 'March', 'April', 'May', 'June',
            'July', 'August', 'September', 'October', 'November', 'December'
        ];
        currentMonthYearSpan.textContent = `${monthNames[month]} ${year}`;
        
        // Add previous month's trailing days
        const prevMonth = month === 0 ? 11 : month - 1;
        const prevYear = month === 0 ? year - 1 : year;
        const prevMonthDays = new Date(prevYear, prevMonth + 1, 0).getDate();
        
        for (let i = startingDayOfWeek - 1; i >= 0; i--) {
            const dayElement = createDayElement(prevMonthDays - i, true, prevMonth, prevYear);
            calendarBody.appendChild(dayElement);
        }
        
        // Add current month's days
        for (let day = 1; day <= daysInMonth; day++) {
            const dayElement = createDayElement(day, false, month, year);
            
            // Check if it's today
            if (isCurrentMonth && day === todayDate) {
                dayElement.classList.add('today');
            }
            
            // Add click event to show details
            const dateString = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
            dayElement.addEventListener('click', () => selectDate(dateString, day, month, year));
            
            calendarBody.appendChild(dayElement);
        }
        
        // Add next month's leading days
        const totalCells = calendarBody.children.length;
        const remainingCells = 42 - totalCells; // 6 rows × 7 days = 42 cells
        const nextMonth = month === 11 ? 0 : month + 1;
        const nextYear = month === 11 ? year + 1 : year;
        
        for (let day = 1; day <= remainingCells; day++) {
            const dayElement = createDayElement(day, true, nextMonth, nextYear);
            calendarBody.appendChild(dayElement);
        }
    }
    
    // Create a day element
    function createDayElement(day, isOtherMonth, month, year) {
        const dayElement = document.createElement('div');
        dayElement.className = 'calendar-day';
        if (isOtherMonth) {
            dayElement.classList.add('other-month');
        }
        
        const dayNumber = document.createElement('div');
        dayNumber.className = 'day-number';
        dayNumber.textContent = day;
        dayElement.appendChild(dayNumber);
        
        // Add click event for other month days too
        if (isOtherMonth) {
            const dateString = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
            dayElement.addEventListener('click', () => selectDate(dateString, day, month, year));
        }
        
        return dayElement;
    }
    
    // Select a date and show details
    function selectDate(dateString, day, month, year) {
        // Remove previous selection
        const previousSelected = document.querySelector('.calendar-day.selected');
        if (previousSelected) {
            previousSelected.classList.remove('selected');
        }
        
        // Add selection to clicked day
        const allDays = document.querySelectorAll('.calendar-day');
        allDays.forEach(dayEl => {
            const dayNum = parseInt(dayEl.querySelector('.day-number').textContent);
            if (dayNum === day) {
                const isOtherMonth = dayEl.classList.contains('other-month');
                if (!isOtherMonth || 
                    (month !== currentMonth || year !== currentYear)) {
                    dayEl.classList.add('selected');
                    selectedDay = { day, month, year, dateString };
                }
            }
        });
        
        // Update selected date display
        const monthNames = [
            'January', 'February', 'March', 'April', 'May', 'June',
            'July', 'August', 'September', 'October', 'November', 'December'
        ];
        selectedDateSpan.textContent = `${monthNames[month]} ${day}, ${year}`;
        
        // Show date details
        showDateDetails(dateString);
    }
    
    // Show details for the selected date
    function showDateDetails(dateString) {
        shiftContent.innerHTML = `
            <div class="no-selection">
                <span class="material-icons no-selection-icon">event</span>
                <p>No schedule information for this date</p>
                <small style="color: #999; margin-top: 8px; display: block;">Selected: ${dateString}</small>
            </div>
        `;
    }
    
    // Navigation: Previous month
    prevMonthBtn.addEventListener('click', () => {
        currentMonth--;
        if (currentMonth < 0) {
            currentMonth = 11;
            currentYear--;
        }
        generateCalendar(currentMonth, currentYear);
    });
    
    // Navigation: Next month
    nextMonthBtn.addEventListener('click', () => {
        currentMonth++;
        if (currentMonth > 11) {
            currentMonth = 0;
            currentYear++;
        }
        generateCalendar(currentMonth, currentYear);
    });
    
    // Initialize calendar with current month
    generateCalendar(currentMonth, currentYear);
});
</script>