<?php require_once APP_ROOT . '/views/inc/components/header.php'; ?>
<?php require_once APP_ROOT . '/views/components/v_adminsidebar.php'; ?>

<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/css/style.css">

<!-- Material Icons -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<!-- Link to Officer Calendar CSS -->
<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/css/admin/officer_calendar_style.css">

<!-- Back Button -->
<button class="tertiary-btn" style="display:flex; width:100px; margin: 20px;align-items:center;" onclick="history.back()"> 
    <span class="material-symbols-outlined" style="font-size:18px;">arrow_back</span>
    Back
</button>

<!-- Officer Info Header -->
<div class="officer-info-header">
    <h2><?php echo htmlspecialchars($data['officer']->name ?? 'Officer'); ?>'s Calendar</h2>
    <p><strong>Officer ID:</strong> <?php echo htmlspecialchars($data['officer']->officerID ?? 'N/A'); ?></p>
    <p><strong>Rank:</strong> <?php echo htmlspecialchars($data['officer']->rank ?? 'N/A'); ?></p>
</div>

<!-- Schedule Content -->
<div class="main-content">
    <div class="schedule-layout">
        <!-- Calendar Section -->
        <div class="calendar-container">
            <div class="calendar-controls">
                <button class="nav-btn" id="prevMonth">
                    <span class="material-icons">chevron_left</span>
                </button>
                <div class="current-month-year">
                    <span id="currentMonthYear">December 2024</span>
                </div>
                <button class="nav-btn" id="nextMonth">
                    <span class="material-icons">chevron_right</span>
                </button>
            </div>

            <div class="calendar">
                <div class="calendar-header">
                    <div class="day-name">MON</div>
                    <div class="day-name">TUE</div>
                    <div class="day-name">WED</div>
                    <div class="day-name">THU</div>
                    <div class="day-name">FRI</div>
                    <div class="day-name">SAT</div>
                    <div class="day-name">SUN</div>
                </div>
                
                <div class="calendar-body" id="calendarBody">
                    <!-- Calendar dates will be generated by JavaScript -->
                </div>
            </div>
            
            <div class="calendar-legend">
                <div class="legend-item">
                    <div class="legend-color work-day"></div>
                    <span>Work Day</span>
                </div>
                <div class="legend-item">
                    <div class="legend-color leave-day"></div>
                    <span>Approved Leave</span>
                </div>
                <div class="legend-item">
                    <div class="legend-color today"></div>
                    <span>Today</span>
                </div>
            </div>
        </div>

        <!-- Shift Details Panel -->
        <div class="shift-details-panel">
            <div class="shift-details" id="shiftDetails">
                <div class="shift-header">
                    <h3>Schedule Details</h3>
                    <span class="selected-date" id="selectedDate">Select a date</span>
                </div>
                
                <div class="shift-content" id="shiftContent">
                    <div class="no-selection">
                        <span class="material-icons no-selection-icon">event</span>
                        <p>Click on a date to view the officer's schedule</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Pass PHP data to JavaScript -->
<script>
    // Assignment data
    const assignmentData = <?php echo json_encode($data['assignments'] ?? []); ?>;
    
    // Leave dates data
    const leaveDatesData = <?php echo json_encode($data['leaveDates'] ?? []); ?>;
    
    // Officer ID for AJAX requests
    const officerId = <?php echo json_encode($data['officer']->user_id ?? null); ?>;
    
    // Base URL for AJAX requests
    const baseURL = '<?php echo URL_ROOT; ?>';
</script>

<script src="<?php echo URL_ROOT; ?>/js/components/sidebar.js"></script>
<script src="<?php echo URL_ROOT; ?>/js/admin/officer_calendar.js"></script>
<?php require_once APP_ROOT . '/views/inc/components/footer.php'; ?>
