<?php require_once APP_ROOT . '/views/inc/components/header.php'; ?>
<?php require_once APP_ROOT . '/views/components/v_premiseofficer_sidebar.php'; ?>


<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/css/style.css">



<!-- Material Icons -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<!-- Link to Schedule CSS -->
<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/css/premiseOfficer/schedule_style.css">

<!-- Schedule Content -->
<div class="main-content">
    <div class="schedule-layout">
        <!-- Calendar Section -->
        <div class="calendar-container">
            <div class="calendar-controls">
                <button class="nav-btn" id="prevMonth">
                    <span class="material-icons">chevron_left</span>
                </button>
                <div class="current-month-year">
                    <span id="currentMonthYear">December 2024</span>
                </div>
                <button class="nav-btn" id="nextMonth">
                    <span class="material-icons">chevron_right</span>
                </button>
            </div>

            <div class="calendar">
                <div class="calendar-header">
                    <div class="day-name">MON</div>
                    <div class="day-name">TUE</div>
                    <div class="day-name">WED</div>
                    <div class="day-name">THU</div>
                    <div class="day-name">FRI</div>
                    <div class="day-name">SAT</div>
                    <div class="day-name">SUN</div>
                </div>
                
                <div class="calendar-body" id="calendarBody">
                    <!-- Calendar dates will be generated by JavaScript -->
                </div>
            </div>
            
            <div class="calendar-legend">
                <div class="legend-item">
                    <div class="legend-color work-day"></div>
                    <span>Work Day</span>
                </div>
                <div class="legend-item">
                    <div class="legend-color leave-day"></div>
                    <span>Approved Leave</span>
                </div>
                <div class="legend-item">
                    <div class="legend-color today"></div>
                    <span>Today</span>
                </div>
            </div>
        </div>

        <!-- Shift Details Panel -->
        <div class="shift-details-panel">
            <div class="shift-details" id="shiftDetails">
                <div class="shift-header">
                    <h3>Schedule Details</h3>
                    <span class="selected-date" id="selectedDate">Select a date</span>
                </div>
                
                <div class="shift-content" id="shiftContent">
                    <div class="no-selection">
                        <span class="material-icons no-selection-icon">event</span>
                        <p>Click on a date to view your schedule</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Pass PHP data to JavaScript -->
<script>
    // Assignment data
    const assignmentData = <?php echo json_encode($data['assignments'] ?? []); ?>;
    
    // Leave dates data
    const leaveDatesData = <?php echo json_encode($data['leaveDates'] ?? []); ?>;
    
    // Base URL for AJAX requests
    const baseURL = '<?php echo URL_ROOT; ?>';
    
    // Debug output
    console.log('Assignment Data:', assignmentData);
    console.log('Leave Dates Data:', leaveDatesData);
    console.log('Base URL:', baseURL);
</script>

<script src="<?php echo URL_ROOT; ?>/js/components/sidebar.js"></script>
<script src="<?php echo URL_ROOT; ?>/js/premiseOfficer/schedule.js"></script>
<?php require_once APP_ROOT . '/views/inc/components/footer.php'; ?>